version: '3.8'

services:
  # AI Processing Backend with Integrated Tools (Dev B + C's work)
  ai-backend:
    build: ../../ai_processing
    ports:
      - "5167:5167"
    environment:
      - TIDB_CONNECTION_STRING=${TIDB_CONNECTION_STRING}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OLLAMA_URL=http://ollama:11434
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - HOST=0.0.0.0
      - PORT=5167
      - ENVIRONMENT=development
    depends_on:
      - ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5167/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama AI Service (for local development)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Dashboard (Dev D's work) - Optional for local testing
  frontend:
    build: ../../frontend_dashboard
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5167
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on:
      - ai-backend
    restart: unless-stopped
    profiles:
      - frontend  # Only start with --profile frontend

volumes:
  ollama_data:
    driver: local

networks:
  default:
    name: scrumbot-dev-network
    driver: bridge